# Generated by Django 5.1.5 on 2025-01-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('idRoom', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=45)),
                ('typeRoom', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
                ('state', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('superadmin', 'SuperAdmin'), ('client', 'Cliente')], max_length=10)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('idBooking', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('state', models.CharField(max_length=20)),
                ('idClientFK', models.ForeignKey(db_column='idClientFK', on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('idRoomFK', models.ForeignKey(db_column='idRoomFK', on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('idPayment', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('paymentDate', models.DateField()),
                ('paymentMethod', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=20)),
                ('idBooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.booking')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='idUserFK',
            field=models.ForeignKey(db_column='idUserFK', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
