# Generated by Django 5.1.5 on 2025-01-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentMethod',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Crédito o Débitp')], max_length=8),
        ),
        migrations.AlterField(
            model_name='room',
            name='state',
            field=models.CharField(choices=[('ocupada', 'Ocupada'), ('disponible', 'Disponible'), ('mantenimiento', 'En mantenimiento')], max_length=14),
        ),
    ]
