# Generated by Django 5.1.5 on 2025-01-26 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_payment_paymentmethod_alter_room_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='idUserFK',
            field=models.ForeignKey(db_column='idUserFK', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada')], max_length=10),
        ),
    ]
