# Generated by Django 5.1.5 on 2025-02-06 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_booking_state_alter_client_iduserfk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='idUserFK',
            field=models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.user'),
        ),
    ]
